includes = ["**/*.dfy", "../target/cs/src/Z3Interface.cs"]
excludes = ["**/flycheck_*"]

[options]
type-system-refresh = true
general-traits = "datatype"
general-newtypes = true
standard-libraries = true